// Development-only presentation data for deterministic Remote Jobs card QA.
// It never submits, refreshes, pauses, or terminates a real job.
export const REMOTE_JOBS_VISUAL_FIXTURE = Object.freeze([
  Object.freeze({
    job_id: "fixture-job-running-01",
    external_id: "sandbox-running-long-identifier-01",
    provider: "e2b",
    status: "running",
    view: Object.freeze({
      workload_kind: "relaxation",
      current_phase: "execute",
      phase_label: "Relaxation",
      show_progress: true,
      phase_plan: Object.freeze([
        Object.freeze({ key: "prepare", label: "Prepare inputs", progress_applicable: false }),
        Object.freeze({ key: "submit", label: "Submit Sandbox", progress_applicable: false }),
        Object.freeze({ key: "queue", label: "Stage runtime", progress_applicable: false }),
        Object.freeze({ key: "execute", label: "Relaxation", progress_applicable: true }),
        Object.freeze({ key: "collect", label: "Collect outputs", progress_applicable: false }),
        Object.freeze({ key: "validate", label: "Verify structure", progress_applicable: false }),
      ]),
      progress: Object.freeze({ current: 64, total: 100, unit: "ionic steps" }),
    }),
    specification: Object.freeze({
      project_id: "fixture-project",
      template: "dpa4-cu131-5090",
      timeout: 7200,
      lifecycle: Object.freeze({ on_timeout: "pause", auto_resume: true }),
      env: Object.freeze({ FIXTURE_TOKEN: "never-render-this-value" }),
    }),
    snapshot: Object.freeze({ provider_status: "running", progress_percent: 64 }),
  }),
  Object.freeze({
    job_id: "fixture-job-paused-02",
    external_id: "sandbox-paused-02",
    provider: "e2b",
    status: "paused",
    view: Object.freeze({
      workload_kind: "relaxation",
      current_phase: "queue",
      phase_label: "Stage runtime",
      show_progress: false,
      phase_plan: Object.freeze([
        Object.freeze({ key: "prepare", label: "Prepare inputs", progress_applicable: false }),
        Object.freeze({ key: "submit", label: "Submit Sandbox", progress_applicable: false }),
        Object.freeze({ key: "queue", label: "Stage runtime", progress_applicable: false }),
        Object.freeze({ key: "execute", label: "Relaxation", progress_applicable: true }),
        Object.freeze({ key: "collect", label: "Collect outputs", progress_applicable: false }),
        Object.freeze({ key: "validate", label: "Verify structure", progress_applicable: false }),
      ]),
      progress: Object.freeze({ current: 41, total: 100, unit: "ionic steps" }),
    }),
    specification: Object.freeze({
      project_id: "fixture-project",
      template: "doc-compiler",
      timeout: 3600,
      lifecycle: Object.freeze({ on_timeout: "pause", auto_resume: false }),
    }),
    snapshot: Object.freeze({ provider_status: "paused" }),
  }),
  Object.freeze({
    job_id: "fixture-job-collected-03",
    external_id: "batch-collected-03",
    provider: "bohrium",
    status: "collected",
    specification: Object.freeze({
      project_id: "fixture-project",
      job_name: "collect-results",
      machine_type: "c32_m64_cpu",
      image_address: "registry.example/fixture:latest",
      max_run_time: 14400,
      command: "fixture command contents are intentionally hidden",
      result_path: "/bohr-results",
    }),
    snapshot: Object.freeze({ provider_status: "completed" }),
  }),
  Object.freeze({
    job_id: "fixture-job-failed-04",
    external_id: "sandbox-failed-04",
    provider: "e2b",
    status: "failed",
    error: "Fixture error text verifies single-line truncation without invoking a provider.",
    specification: Object.freeze({
      project_id: "fixture-project",
      template: "failed-template",
      timeout: 1800,
    }),
    snapshot: Object.freeze({ provider_status: "failed" }),
  }),
]);
