const defaultFrameDark = {
  "--skin-body-surface": "#121616",
  "--skin-shell-border-width": "1px",
  "--skin-shell-border-color": "#2C3331",
  "--skin-shell-radius": "8px",
  "--skin-shell-shadow": "none",
  "--skin-shell-background": "#191E1E",
  "--skin-graph-surface": "#191E1E",
  "--skin-graph-surface-tone": "dark",
  "--skin-chat-surface": "#191E1E",
  "--skin-side-surface": "#191E1E",
  "--skin-composer-surface": "#222828",
  "--skin-screw-color": "#747D79",
  "--skin-screw-size": "7px",
  "--skin-screw-opacity": "0",
  "--skin-control-background": "#191E1E",
  "--skin-control-border-color": "#3D4743",
  "--skin-control-shadow": "none",
  "--skin-control-pressed-shadow": "none",
  "--skin-display-font": "'Manrope', sans-serif",
  "--skin-label-font": "'Manrope', sans-serif",
  "--skin-display-letter-spacing": "0px",
  "--skin-label-transform": "none",
};

const defaultFrameLight = {
  ...defaultFrameDark,
  "--skin-body-surface": "#ECEDEF",
  "--skin-shell-border-color": "#D4D7DA",
  "--skin-shell-background": "#F7F7F6",
  "--skin-graph-surface": "#F7F7F6",
  "--skin-graph-surface-tone": "light",
  "--skin-chat-surface": "#F7F7F6",
  "--skin-side-surface": "#F7F7F6",
  "--skin-composer-surface": "#FFFFFF",
  "--skin-screw-color": "#626972",
  "--skin-control-background": "#F7F7F6",
  "--skin-control-border-color": "#D4D7DA",
};

const rackFrame = {
  "--skin-shell-border-width": "2px",
  "--skin-shell-border-color": "#1B1D22",
  "--skin-shell-radius": "14px",
  "--skin-shell-shadow": "0 5px 0 #1B1D22, 0 13px 24px rgba(23, 25, 31, 0.24)",
  "--skin-screw-color": "#B7B8B6",
  "--skin-screw-size": "8px",
  "--skin-screw-opacity": "1",
  "--skin-control-border-color": "#1B1D22",
  "--skin-control-shadow": "0 3px 0 #1B1D22, 0 6px 10px rgba(23, 25, 31, 0.18)",
  "--skin-control-pressed-shadow": "0 1px 0 #1B1D22, 0 2px 4px rgba(23, 25, 31, 0.16)",
  "--skin-display-font": "'Arial Narrow', 'Cascadia Mono', sans-serif",
  "--skin-label-font": "'Cascadia Mono', 'Consolas', monospace",
  "--skin-display-letter-spacing": "1px",
  "--skin-label-transform": "uppercase",
};

export const DEFAULT_SKIN = Object.freeze({
  id: "matcreator-default",
  name: "MatCreator Default",
  description: "The familiar MatCreator workspace with restrained scientific surfaces.",
  version: "1.0.0",
  skinSchemaVersion: 1,
  styleRecipe: { id: "standard", apiVersion: 1 },
  defaultVariant: "dark",
  preview: { swatches: ["#121616", "#191E1E", "#C3644D"] },
  variants: {
    dark: {
      label: "Dark",
      colorScheme: "dark",
      tokens: {
        "--bg-canvas": "#121616",
        "--bg-surface": "#191E1E",
        "--bg-elevated": "#222828",
        "--text-primary": "#EBEEEC",
        "--text-secondary": "#ADB5B1",
        "--border-default": "#3D4743",
        "--accent-primary": "#C3644D",
        "--focus-ring": "#D18470",
        "--success": "#6E9B89",
        "--warning": "#D0A052",
        "--danger": "#D16969",
        ...defaultFrameDark,
      },
    },
    light: {
      label: "Light",
      colorScheme: "light",
      tokens: {
        "--bg-canvas": "#ECEDEF",
        "--bg-surface": "#F7F7F6",
        "--bg-elevated": "#FFFFFF",
        "--text-primary": "#22262C",
        "--text-secondary": "#626972",
        "--border-default": "#D4D7DA",
        "--accent-primary": "#315C9A",
        "--focus-ring": "#6484B2",
        "--success": "#4D786A",
        "--warning": "#B5802B",
        "--danger": "#B4494E",
        ...defaultFrameLight,
      },
    },
  },
});

export const RACK_LAB_SKIN = Object.freeze({
  id: "rack-lab",
  name: "Rack Lab",
  description: "A tactile instrument-panel skin with cream enamel, graphite hardware, and signal yellow.",
  version: "0.1.0",
  skinSchemaVersion: 1,
  styleRecipe: { id: "rack-lab", apiVersion: 1 },
  defaultVariant: "light",
  preview: { swatches: ["#F4F3EE", "#FFC400", "#343640"] },
  variants: {
    light: {
      label: "Cream",
      colorScheme: "light",
      tokens: {
        "--bg-canvas": "#E8E7E1",
        "--bg-surface": "#F4F3EE",
        "--bg-elevated": "#FFFDF8",
        "--bg-hover": "#E8E5DC",
        "--bg-active": "#FFD337",
        "--text-primary": "#17191F",
        "--text-secondary": "#55575E",
        "--text-muted": "#73747A",
        "--text-disabled": "#A4A4A1",
        "--border-subtle": "#C5C3BC",
        "--border-default": "#1B1D22",
        "--border-strong": "#17191F",
        "--accent-primary": "#8A6500",
        "--accent-primary-hover": "#6F5200",
        "--accent-primary-active": "#5C4400",
        "--accent-primary-soft": "#FFE681",
        "--accent-on-primary": "#FFFDF8",
        "--accent-secondary": "#7767FF",
        "--accent-secondary-soft": "#E5E0FF",
        "--selection": "#FFE681",
        "--focus-ring": "#7767FF",
        "--success": "#2E7B58",
        "--warning": "#B87500",
        "--danger": "#B9444D",
        "--info": "#316F9A",
        "--panel-rgb": "244, 243, 238",
        "--accent-rgb": "138, 101, 0",
        "--terminal-bg": "#343640",
        "--terminal-border": "#1B1D22",
        "--terminal-text": "#F8F5EA",
        "--terminal-muted": "#B9B8B0",
        "--session-item-hover-bg": "#EEEAE0",
        "--session-item-hover-border": "#9A8D62",
        "--session-item-active-bg": "#FFC400",
        "--session-item-active-border": "#1B1D22",
        "--agent-bg-1": "#FFFDF8",
        "--agent-bg-2": "#F4F3EE",
        "--agent-border": "#1B1D22",
        "--agent-box-shadow-color": "rgba(23, 25, 31, 0.16)",
        "--user-bg-1": "#FFC400",
        "--user-bg-2": "#FFD337",
        "--user-border": "#1B1D22",
        "--user-box-shadow-color": "rgba(23, 25, 31, 0.18)",
        "--skin-body-surface": "#E8E7E1",
        "--skin-shell-background": "#F4F3EE",
        "--skin-graph-surface": "#343640",
        "--skin-chat-surface": "#F4F3EE",
        "--skin-side-surface": "#F4F3EE",
        "--skin-composer-surface": "#FFC400",
        "--skin-control-background": "#F4F3EE",
        ...rackFrame,
        "--skin-graph-surface-tone": "light",
        "--skin-graph-droplet-fill-alpha": "0.11",
      },
    },
    dark: {
      label: "Graphite",
      colorScheme: "dark",
      tokens: {
        "--bg-canvas": "#20222A",
        "--bg-surface": "#343640",
        "--bg-elevated": "#41434E",
        "--bg-hover": "#4A4C56",
        "--bg-active": "#595B65",
        "--text-primary": "#F7F4EA",
        "--text-secondary": "#C3C0B7",
        "--text-muted": "#92918D",
        "--text-disabled": "#696A70",
        "--border-subtle": "#23252C",
        "--border-default": "#17191F",
        "--border-strong": "#0F1014",
        "--accent-primary": "#FFC400",
        "--accent-primary-hover": "#FFD337",
        "--accent-primary-active": "#DDA900",
        "--accent-primary-soft": "#554716",
        "--accent-on-primary": "#17191F",
        "--accent-secondary": "#9B90FF",
        "--accent-secondary-soft": "#39335F",
        "--selection": "#5E501C",
        "--focus-ring": "#A89FFF",
        "--success": "#70B38F",
        "--warning": "#E0A943",
        "--danger": "#E27076",
        "--info": "#78ABD0",
        "--panel-rgb": "52, 54, 64",
        "--accent-rgb": "255, 196, 0",
        "--terminal-bg": "#17191F",
        "--terminal-border": "#0F1014",
        "--terminal-text": "#F7F4EA",
        "--terminal-muted": "#A9A79F",
        "--session-item-hover-bg": "#454751",
        "--session-item-hover-border": "#686A73",
        "--session-item-active-bg": "#5E501C",
        "--session-item-active-border": "#FFC400",
        "--agent-bg-1": "#41434E",
        "--agent-bg-2": "#343640",
        "--agent-border": "#17191F",
        "--agent-box-shadow-color": "rgba(15, 16, 20, 0.28)",
        "--user-bg-1": "#554716",
        "--user-bg-2": "#343640",
        "--user-border": "#FFC400",
        "--user-box-shadow-color": "rgba(15, 16, 20, 0.32)",
        "--skin-body-surface": "#20222A",
        "--skin-shell-background": "#343640",
        "--skin-graph-surface": "#2B2D36",
        "--skin-chat-surface": "#343640",
        "--skin-side-surface": "#343640",
        "--skin-composer-surface": "#FFC400",
        "--skin-control-background": "#41434E",
        ...rackFrame,
        "--skin-graph-surface-tone": "dark",
        "--skin-graph-droplet-fill-alpha": "0.12",
      },
    },
  },
});

export const BUILTIN_SKINS = Object.freeze([
  DEFAULT_SKIN,
  RACK_LAB_SKIN,
]);
